from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

FIELDS = [
    {
        "fieldname": "custom_reference_user",
        "fieldtype": "Link",
        "options": "User",
        "label": "Reference",
        "insert_after": "company_name",
    },

    # ── Prospect & Profiling ─────────────────────────────────────
    {
        "fieldname": "custom_prospect_section",
        "fieldtype": "Section Break",
        "label": "Prospect & Profiling",
        "insert_after": "custom_reference_user",
    },
    {
        "fieldname": "custom_source_url",
        "fieldtype": "Data",
        "label": "Source URL",
        "options": "URL",
        "insert_after": "custom_prospect_section",
    },
    {
        "fieldname": "custom_company_type",
        "fieldtype": "Select",
        "label": "Company Type",
        "options": "\nGeneral Contractor\nRoofing Specialist\nMasonry\nEvent Organizer",
        "insert_after": "custom_source_url",
        "in_list_view": 1,
        "in_filter": 1,
    },
    {
        "fieldname": "custom_website",
        "fieldtype": "Data",
        "label": "Website",
        "options": "URL",
        "insert_after": "custom_company_type",
    },
    {
        "fieldname": "custom_country",
        "fieldtype": "Data",
        "label": "Country",
        "insert_after": "custom_website",
        "in_filter": 1,
    },
    {
        "fieldname": "custom_city",
        "fieldtype": "Data",
        "label": "City",
        "insert_after": "custom_country",
        "in_filter": 1,
    },
    {
        "fieldname": "custom_col_break_prospect",
        "fieldtype": "Column Break",
        "insert_after": "custom_company_type",
    },
    {
        "fieldname": "custom_prospect_status",
        "fieldtype": "Select",
        "label": "Prospect Status",
        "options": "\nScraped\nRaw\nVetted\nDisqualified",
        "insert_after": "custom_col_break_prospect",
        "in_list_view": 1,
        "in_filter": 1,
        "default": "Scraped",
    },

    # ── Survey / Technical ───────────────────────────────────────
    {
        "fieldname": "custom_survey_section",
        "fieldtype": "Section Break",
        "label": "Survey & Technical",
        "insert_after": "custom_prospect_status",
        "collapsible": 1,
    },
    {
        "fieldname": "custom_survey_status",
        "fieldtype": "Select",
        "label": "Survey Status",
        "options": "\nPending\nScheduled\nCompleted\nCancelled",
        "insert_after": "custom_survey_section",
        "in_filter": 1,
    },
    {
        "fieldname": "custom_survey_datetime",
        "fieldtype": "Datetime",
        "label": "Scheduled Survey Date/Time",
        "insert_after": "custom_survey_status",
    },
    {
        "fieldname": "custom_assigned_surveyor",
        "fieldtype": "Link",
        "label": "Assigned Surveyor",
        "options": "User",
        "insert_after": "custom_survey_datetime",
    },
    {
        "fieldname": "custom_col_break_survey",
        "fieldtype": "Column Break",
        "insert_after": "custom_assigned_surveyor",
    },
    {
        "fieldname": "custom_site_address",
        "fieldtype": "Data",
        "label": "Site Address",
        "insert_after": "custom_col_break_survey",
    },
    {
        "fieldname": "custom_scaffolding_purpose",
        "fieldtype": "Select",
        "label": "Scaffolding Purpose",
        "options": "\nFacade Work\nRoofing\nBricklaying\nShoring\nIndoor/Suspended",
        "insert_after": "custom_site_address",
    },
    {
        "fieldname": "custom_structure_type",
        "fieldtype": "Select",
        "label": "Structure Type",
        "options": "\nCuplock\nRinglock/System\nTube and Clamp\nFrame Scaffolding",
        "insert_after": "custom_scaffolding_purpose",
    },
    {
        "fieldname": "custom_dimensions_section",
        "fieldtype": "Section Break",
        "label": "Estimated Dimensions Required",
        "insert_after": "custom_structure_type",
        "collapsible": 1,
    },
    {
        "fieldname": "custom_max_height",
        "fieldtype": "Float",
        "label": "Max Height Needed (m)",
        "insert_after": "custom_dimensions_section",
    },
    {
        "fieldname": "custom_col_break_dimensions",
        "fieldtype": "Column Break",
        "insert_after": "custom_max_height",
    },
    {
        "fieldname": "custom_linear_length",
        "fieldtype": "Float",
        "label": "Linear Length/Run (m)",
        "insert_after": "custom_col_break_dimensions",
    },
    {
        "fieldname": "custom_site_conditions_section",
        "fieldtype": "Section Break",
        "label": "Site Conditions",
        "insert_after": "custom_linear_length",
        "collapsible": 1,
    },
    {
        "fieldname": "custom_ground_conditions",
        "fieldtype": "Select",
        "label": "Ground/Terrain Conditions",
        "options": "\nConcrete\nSoft Soil\nUneven Slopes",
        "insert_after": "custom_site_conditions_section",
    },
    {
        "fieldname": "custom_access_obstacles",
        "fieldtype": "Small Text",
        "label": "Access/Obstacles",
        "insert_after": "custom_ground_conditions",
    },

    # ── Commercial / Client ──────────────────────────────────────
    {
        "fieldname": "custom_commercial_section",
        "fieldtype": "Section Break",
        "label": "Commercial & Logistics",
        "insert_after": "custom_access_obstacles",
        "collapsible": 1,
    },
    {
        "fieldname": "custom_client_account_number",
        "fieldtype": "Data",
        "label": "Client Account Number",
        "insert_after": "custom_commercial_section",
        "read_only": 1,
    },
    {
        "fieldname": "custom_rental_start_date",
        "fieldtype": "Date",
        "label": "Rental Start Date",
        "insert_after": "custom_client_account_number",
    },
    {
        "fieldname": "custom_rental_end_date",
        "fieldtype": "Date",
        "label": "Expected Rental End Date",
        "insert_after": "custom_rental_start_date",
    },
    {
        "fieldname": "custom_dismantle_date",
        "fieldtype": "Date",
        "label": "Actual Handover/Dismantle Date",
        "insert_after": "custom_rental_end_date",
    },
    {
        "fieldname": "custom_col_break_commercial",
        "fieldtype": "Column Break",
        "insert_after": "custom_dismantle_date",
    },
    {
        "fieldname": "custom_billing_frequency",
        "fieldtype": "Select",
        "label": "Billing Frequency",
        "options": "\nWeekly\nMonthly\nFixed Project Rate",
        "insert_after": "custom_col_break_commercial",
    },
    {
        "fieldname": "custom_weekly_rate",
        "fieldtype": "Currency",
        "label": "Weekly Rental Rate",
        "insert_after": "custom_billing_frequency",
    },
    {
        "fieldname": "custom_charges_section",
        "fieldtype": "Section Break",
        "label": "One-Time Charges",
        "insert_after": "custom_weekly_rate",
        "collapsible": 1,
    },
    {
        "fieldname": "custom_transport_fee",
        "fieldtype": "Currency",
        "label": "Transport/Delivery Fee",
        "insert_after": "custom_charges_section",
    },
    {
        "fieldname": "custom_erection_fee",
        "fieldtype": "Currency",
        "label": "Erection/Assembly Fee",
        "insert_after": "custom_transport_fee",
    },
    {
        "fieldname": "custom_col_break_charges",
        "fieldtype": "Column Break",
        "insert_after": "custom_erection_fee",
    },
    {
        "fieldname": "custom_dismantling_fee",
        "fieldtype": "Currency",
        "label": "Dismantling Fee",
        "insert_after": "custom_col_break_charges",
    },
    {
        "fieldname": "custom_required_permits",
        "fieldtype": "Attach",
        "label": "Required Permits",
        "insert_after": "custom_dismantling_fee",
    },
    {
        "fieldname": "custom_handover_certificate",
        "fieldtype": "Attach",
        "label": "Handover Certificate (GA3 / Scafftag)",
        "insert_after": "custom_required_permits",
    },

    # ── Social & Web ─────────────────────────────────────────────
    {
        "fieldname": "custom_social_section",
        "fieldtype": "Section Break",
        "label": "Social & Web",
        "insert_after": "custom_handover_certificate",
        "collapsible": 1,
    },
    {
        "fieldname": "custom_facebook",
        "fieldtype": "Data",
        "label": "Facebook",
        "insert_after": "custom_social_section",
    },
    {
        "fieldname": "custom_instagram",
        "fieldtype": "Data",
        "label": "Instagram",
        "insert_after": "custom_facebook",
    },
    {
        "fieldname": "custom_col_break_social",
        "fieldtype": "Column Break",
        "insert_after": "custom_instagram",
    },
    {
        "fieldname": "custom_tiktok",
        "fieldtype": "Data",
        "label": "TikTok",
        "insert_after": "custom_col_break_social",
    },
    {
        "fieldname": "custom_x",
        "fieldtype": "Data",
        "label": "X",
        "insert_after": "custom_tiktok",
    },
    {
        "fieldname": "custom_linkedin",
        "fieldtype": "Data",
        "label": "LinkedIn",
        "insert_after": "custom_x",
    },

    # ── System & Lifecycle (mostly hidden metadata) ──────────────
    {
        "fieldname": "custom_lifecycle_section",
        "fieldtype": "Section Break",
        "label": "Lifecycle Tracking",
        "insert_after": "custom_handover_certificate",
        "collapsible": 1,
    },
    {
        "fieldname": "custom_lifecycle_stage",
        "fieldtype": "Select",
        "label": "Current Lifecycle Stage",
        "options": "\nProspect\nLead (Survey Requested)\nLead (Survey Completed)\nActive Client\nChurned/Archived",
        "insert_after": "custom_lifecycle_section",
        "in_list_view": 1,
        "in_filter": 1,
        "default": "Prospect",
    },
    {
        "fieldname": "custom_scraping_batch_id",
        "fieldtype": "Data",
        "label": "Scraping Batch ID",
        "insert_after": "custom_lifecycle_stage",
    },
    {
        "fieldname": "custom_col_break_lifecycle",
        "fieldtype": "Column Break",
        "insert_after": "custom_scraping_batch_id",
    },
    {
        "fieldname": "custom_date_scraped",
        "fieldtype": "Date",
        "label": "Date Scraped",
        "insert_after": "custom_col_break_lifecycle",
        "hidden": 1,
    },
    {
        "fieldname": "custom_date_converted_to_lead",
        "fieldtype": "Date",
        "label": "Date Converted to Lead",
        "insert_after": "custom_date_scraped",
        "hidden": 1,
    },
    {
        "fieldname": "custom_date_became_client",
        "fieldtype": "Date",
        "label": "Date Became Client",
        "insert_after": "custom_date_converted_to_lead",
        "hidden": 1,
    },
]


def setup():
    create_custom_fields({"Contact": FIELDS}, update=True)
